version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=caqtur
      - POSTGRES_USER= adm
      - POSTGRES_PASSWORD=1518
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
